#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBanOto")]
public partial class luotxemDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertDON_HANG(DON_HANG instance);
  partial void UpdateDON_HANG(DON_HANG instance);
  partial void DeleteDON_HANG(DON_HANG instance);
  partial void InsertHANG_XE(HANG_XE instance);
  partial void UpdateHANG_XE(HANG_XE instance);
  partial void DeleteHANG_XE(HANG_XE instance);
  partial void InsertTAI_KHOAN(TAI_KHOAN instance);
  partial void UpdateTAI_KHOAN(TAI_KHOAN instance);
  partial void DeleteTAI_KHOAN(TAI_KHOAN instance);
  partial void InsertTinTuc(TinTuc instance);
  partial void UpdateTinTuc(TinTuc instance);
  partial void DeleteTinTuc(TinTuc instance);
  partial void InsertXE(XE instance);
  partial void UpdateXE(XE instance);
  partial void DeleteXE(XE instance);
  #endregion
	
	public luotxemDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLBanOtoConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public luotxemDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public luotxemDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public luotxemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public luotxemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<DON_HANG> DON_HANGs
	{
		get
		{
			return this.GetTable<DON_HANG>();
		}
	}
	
	public System.Data.Linq.Table<HANG_XE> HANG_XEs
	{
		get
		{
			return this.GetTable<HANG_XE>();
		}
	}
	
	public System.Data.Linq.Table<TAI_KHOAN> TAI_KHOANs
	{
		get
		{
			return this.GetTable<TAI_KHOAN>();
		}
	}
	
	public System.Data.Linq.Table<TinTuc> TinTucs
	{
		get
		{
			return this.GetTable<TinTuc>();
		}
	}
	
	public System.Data.Linq.Table<XE> XEs
	{
		get
		{
			return this.GetTable<XE>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tintuc_chiTietLuotXem")]
	public int tintuc_chiTietLuotXem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> matin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> luotxem)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matin, luotxem);
		luotxem = ((System.Nullable<int>)(result.GetParameterValue(1)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tintuc_chiTietSLX")]
	public ISingleResult<tintuc_chiTietSLXResult> tintuc_chiTietSLX([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> luotXem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> matin)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), luotXem, matin);
		return ((ISingleResult<tintuc_chiTietSLXResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DON_HANG")]
public partial class DON_HANG : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MaDonHang;
	
	private System.DateTime _NgayTao;
	
	private decimal _DonGia;
	
	private string _HinhThucThanhToan;
	
	private int _MaXe;
	
	private string _TenTaiKhoan;
	
	private string _TrangThaiDonHang;
	
	private EntityRef<TAI_KHOAN> _TAI_KHOAN;
	
	private EntityRef<XE> _XE;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangChanging(int value);
    partial void OnMaDonHangChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnHinhThucThanhToanChanging(string value);
    partial void OnHinhThucThanhToanChanged();
    partial void OnMaXeChanging(int value);
    partial void OnMaXeChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnTrangThaiDonHangChanging(string value);
    partial void OnTrangThaiDonHangChanged();
    #endregion
	
	public DON_HANG()
	{
		this._TAI_KHOAN = default(EntityRef<TAI_KHOAN>);
		this._XE = default(EntityRef<XE>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MaDonHang
	{
		get
		{
			return this._MaDonHang;
		}
		set
		{
			if ((this._MaDonHang != value))
			{
				this.OnMaDonHangChanging(value);
				this.SendPropertyChanging();
				this._MaDonHang = value;
				this.SendPropertyChanged("MaDonHang");
				this.OnMaDonHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime NOT NULL")]
	public System.DateTime NgayTao
	{
		get
		{
			return this._NgayTao;
		}
		set
		{
			if ((this._NgayTao != value))
			{
				this.OnNgayTaoChanging(value);
				this.SendPropertyChanging();
				this._NgayTao = value;
				this.SendPropertyChanged("NgayTao");
				this.OnNgayTaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(11,0) NOT NULL")]
	public decimal DonGia
	{
		get
		{
			return this._DonGia;
		}
		set
		{
			if ((this._DonGia != value))
			{
				this.OnDonGiaChanging(value);
				this.SendPropertyChanging();
				this._DonGia = value;
				this.SendPropertyChanged("DonGia");
				this.OnDonGiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucThanhToan", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string HinhThucThanhToan
	{
		get
		{
			return this._HinhThucThanhToan;
		}
		set
		{
			if ((this._HinhThucThanhToan != value))
			{
				this.OnHinhThucThanhToanChanging(value);
				this.SendPropertyChanging();
				this._HinhThucThanhToan = value;
				this.SendPropertyChanged("HinhThucThanhToan");
				this.OnHinhThucThanhToanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="Int NOT NULL")]
	public int MaXe
	{
		get
		{
			return this._MaXe;
		}
		set
		{
			if ((this._MaXe != value))
			{
				if (this._XE.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaXeChanging(value);
				this.SendPropertyChanging();
				this._MaXe = value;
				this.SendPropertyChanged("MaXe");
				this.OnMaXeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string TenTaiKhoan
	{
		get
		{
			return this._TenTaiKhoan;
		}
		set
		{
			if ((this._TenTaiKhoan != value))
			{
				if (this._TAI_KHOAN.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTenTaiKhoanChanging(value);
				this.SendPropertyChanging();
				this._TenTaiKhoan = value;
				this.SendPropertyChanged("TenTaiKhoan");
				this.OnTenTaiKhoanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiDonHang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string TrangThaiDonHang
	{
		get
		{
			return this._TrangThaiDonHang;
		}
		set
		{
			if ((this._TrangThaiDonHang != value))
			{
				this.OnTrangThaiDonHangChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiDonHang = value;
				this.SendPropertyChanged("TrangThaiDonHang");
				this.OnTrangThaiDonHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_DON_HANG", Storage="_TAI_KHOAN", ThisKey="TenTaiKhoan", OtherKey="TenTaiKhoan", IsForeignKey=true)]
	public TAI_KHOAN TAI_KHOAN
	{
		get
		{
			return this._TAI_KHOAN.Entity;
		}
		set
		{
			TAI_KHOAN previousValue = this._TAI_KHOAN.Entity;
			if (((previousValue != value) 
						|| (this._TAI_KHOAN.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TAI_KHOAN.Entity = null;
					previousValue.DON_HANGs.Remove(this);
				}
				this._TAI_KHOAN.Entity = value;
				if ((value != null))
				{
					value.DON_HANGs.Add(this);
					this._TenTaiKhoan = value.TenTaiKhoan;
				}
				else
				{
					this._TenTaiKhoan = default(string);
				}
				this.SendPropertyChanged("TAI_KHOAN");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XE_DON_HANG", Storage="_XE", ThisKey="MaXe", OtherKey="MaXe", IsForeignKey=true)]
	public XE XE
	{
		get
		{
			return this._XE.Entity;
		}
		set
		{
			XE previousValue = this._XE.Entity;
			if (((previousValue != value) 
						|| (this._XE.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._XE.Entity = null;
					previousValue.DON_HANGs.Remove(this);
				}
				this._XE.Entity = value;
				if ((value != null))
				{
					value.DON_HANGs.Add(this);
					this._MaXe = value.MaXe;
				}
				else
				{
					this._MaXe = default(int);
				}
				this.SendPropertyChanged("XE");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANG_XE")]
public partial class HANG_XE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MaHangXe;
	
	private string _TenHang;
	
	private string _Anh;
	
	private EntitySet<XE> _XEs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangXeChanging(int value);
    partial void OnMaHangXeChanged();
    partial void OnTenHangChanging(string value);
    partial void OnTenHangChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    #endregion
	
	public HANG_XE()
	{
		this._XEs = new EntitySet<XE>(new Action<XE>(this.attach_XEs), new Action<XE>(this.detach_XEs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangXe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MaHangXe
	{
		get
		{
			return this._MaHangXe;
		}
		set
		{
			if ((this._MaHangXe != value))
			{
				this.OnMaHangXeChanging(value);
				this.SendPropertyChanging();
				this._MaHangXe = value;
				this.SendPropertyChanged("MaHangXe");
				this.OnMaHangXeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string TenHang
	{
		get
		{
			return this._TenHang;
		}
		set
		{
			if ((this._TenHang != value))
			{
				this.OnTenHangChanging(value);
				this.SendPropertyChanging();
				this._TenHang = value;
				this.SendPropertyChanged("TenHang");
				this.OnTenHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Anh
	{
		get
		{
			return this._Anh;
		}
		set
		{
			if ((this._Anh != value))
			{
				this.OnAnhChanging(value);
				this.SendPropertyChanging();
				this._Anh = value;
				this.SendPropertyChanged("Anh");
				this.OnAnhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANG_XE_XE", Storage="_XEs", ThisKey="MaHangXe", OtherKey="MaHangXe")]
	public EntitySet<XE> XEs
	{
		get
		{
			return this._XEs;
		}
		set
		{
			this._XEs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_XEs(XE entity)
	{
		this.SendPropertyChanging();
		entity.HANG_XE = this;
	}
	
	private void detach_XEs(XE entity)
	{
		this.SendPropertyChanging();
		entity.HANG_XE = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAI_KHOAN")]
public partial class TAI_KHOAN : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _TenTaiKhoan;
	
	private string _HoTen;
	
	private string _DiaChi;
	
	private string _SoDienThoai;
	
	private string _Email;
	
	private string _MatKhau;
	
	private string _Quyen;
	
	private System.Nullable<bool> _Khoa;
	
	private EntitySet<DON_HANG> _DON_HANGs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    partial void OnKhoaChanging(System.Nullable<bool> value);
    partial void OnKhoaChanged();
    #endregion
	
	public TAI_KHOAN()
	{
		this._DON_HANGs = new EntitySet<DON_HANG>(new Action<DON_HANG>(this.attach_DON_HANGs), new Action<DON_HANG>(this.detach_DON_HANGs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TenTaiKhoan
	{
		get
		{
			return this._TenTaiKhoan;
		}
		set
		{
			if ((this._TenTaiKhoan != value))
			{
				this.OnTenTaiKhoanChanging(value);
				this.SendPropertyChanging();
				this._TenTaiKhoan = value;
				this.SendPropertyChanged("TenTaiKhoan");
				this.OnTenTaiKhoanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
	public string HoTen
	{
		get
		{
			return this._HoTen;
		}
		set
		{
			if ((this._HoTen != value))
			{
				this.OnHoTenChanging(value);
				this.SendPropertyChanging();
				this._HoTen = value;
				this.SendPropertyChanged("HoTen");
				this.OnHoTenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string SoDienThoai
	{
		get
		{
			return this._SoDienThoai;
		}
		set
		{
			if ((this._SoDienThoai != value))
			{
				this.OnSoDienThoaiChanging(value);
				this.SendPropertyChanging();
				this._SoDienThoai = value;
				this.SendPropertyChanged("SoDienThoai");
				this.OnSoDienThoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(30) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string MatKhau
	{
		get
		{
			return this._MatKhau;
		}
		set
		{
			if ((this._MatKhau != value))
			{
				this.OnMatKhauChanging(value);
				this.SendPropertyChanging();
				this._MatKhau = value;
				this.SendPropertyChanged("MatKhau");
				this.OnMatKhauChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Quyen
	{
		get
		{
			return this._Quyen;
		}
		set
		{
			if ((this._Quyen != value))
			{
				this.OnQuyenChanging(value);
				this.SendPropertyChanging();
				this._Quyen = value;
				this.SendPropertyChanged("Quyen");
				this.OnQuyenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="Bit")]
	public System.Nullable<bool> Khoa
	{
		get
		{
			return this._Khoa;
		}
		set
		{
			if ((this._Khoa != value))
			{
				this.OnKhoaChanging(value);
				this.SendPropertyChanging();
				this._Khoa = value;
				this.SendPropertyChanged("Khoa");
				this.OnKhoaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_DON_HANG", Storage="_DON_HANGs", ThisKey="TenTaiKhoan", OtherKey="TenTaiKhoan")]
	public EntitySet<DON_HANG> DON_HANGs
	{
		get
		{
			return this._DON_HANGs;
		}
		set
		{
			this._DON_HANGs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_DON_HANGs(DON_HANG entity)
	{
		this.SendPropertyChanging();
		entity.TAI_KHOAN = this;
	}
	
	private void detach_DON_HANGs(DON_HANG entity)
	{
		this.SendPropertyChanging();
		entity.TAI_KHOAN = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuc")]
public partial class TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MaTin;
	
	private string _Anh;
	
	private string _MoTa;
	
	private string _NoiDung;
	
	private System.DateTime _NgayTao;
	
	private System.Nullable<int> _LuotXem;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinChanging(int value);
    partial void OnMaTinChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    #endregion
	
	public TinTuc()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MaTin
	{
		get
		{
			return this._MaTin;
		}
		set
		{
			if ((this._MaTin != value))
			{
				this.OnMaTinChanging(value);
				this.SendPropertyChanging();
				this._MaTin = value;
				this.SendPropertyChanged("MaTin");
				this.OnMaTinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Anh
	{
		get
		{
			return this._Anh;
		}
		set
		{
			if ((this._Anh != value))
			{
				this.OnAnhChanging(value);
				this.SendPropertyChanging();
				this._Anh = value;
				this.SendPropertyChanged("Anh");
				this.OnAnhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string MoTa
	{
		get
		{
			return this._MoTa;
		}
		set
		{
			if ((this._MoTa != value))
			{
				this.OnMoTaChanging(value);
				this.SendPropertyChanging();
				this._MoTa = value;
				this.SendPropertyChanged("MoTa");
				this.OnMoTaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NoiDung
	{
		get
		{
			return this._NoiDung;
		}
		set
		{
			if ((this._NoiDung != value))
			{
				this.OnNoiDungChanging(value);
				this.SendPropertyChanging();
				this._NoiDung = value;
				this.SendPropertyChanged("NoiDung");
				this.OnNoiDungChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date NOT NULL")]
	public System.DateTime NgayTao
	{
		get
		{
			return this._NgayTao;
		}
		set
		{
			if ((this._NgayTao != value))
			{
				this.OnNgayTaoChanging(value);
				this.SendPropertyChanging();
				this._NgayTao = value;
				this.SendPropertyChanged("NgayTao");
				this.OnNgayTaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
	public System.Nullable<int> LuotXem
	{
		get
		{
			return this._LuotXem;
		}
		set
		{
			if ((this._LuotXem != value))
			{
				this.OnLuotXemChanging(value);
				this.SendPropertyChanging();
				this._LuotXem = value;
				this.SendPropertyChanged("LuotXem");
				this.OnLuotXemChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.XE")]
public partial class XE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MaXe;
	
	private string _TenXe;
	
	private string _TinhTrang;
	
	private decimal _GiaBan;
	
	private string _Model;
	
	private string _HopSo;
	
	private string _NhienLieu;
	
	private string _KieuDanDong;
	
	private string _MauSac;
	
	private int _KmDaDi;
	
	private string _DongXe;
	
	private int _NamSanXuat;
	
	private string _XuatXu;
	
	private string _MoTa;
	
	private string _Anh;
	
	private int _MaHangXe;
	
	private System.Nullable<bool> _CoSan;
	
	private EntitySet<DON_HANG> _DON_HANGs;
	
	private EntityRef<HANG_XE> _HANG_XE;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXeChanging(int value);
    partial void OnMaXeChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnGiaBanChanging(decimal value);
    partial void OnGiaBanChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnHopSoChanging(string value);
    partial void OnHopSoChanged();
    partial void OnNhienLieuChanging(string value);
    partial void OnNhienLieuChanged();
    partial void OnKieuDanDongChanging(string value);
    partial void OnKieuDanDongChanged();
    partial void OnMauSacChanging(string value);
    partial void OnMauSacChanged();
    partial void OnKmDaDiChanging(int value);
    partial void OnKmDaDiChanged();
    partial void OnDongXeChanging(string value);
    partial void OnDongXeChanged();
    partial void OnNamSanXuatChanging(int value);
    partial void OnNamSanXuatChanged();
    partial void OnXuatXuChanging(string value);
    partial void OnXuatXuChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnMaHangXeChanging(int value);
    partial void OnMaHangXeChanged();
    partial void OnCoSanChanging(System.Nullable<bool> value);
    partial void OnCoSanChanged();
    #endregion
	
	public XE()
	{
		this._DON_HANGs = new EntitySet<DON_HANG>(new Action<DON_HANG>(this.attach_DON_HANGs), new Action<DON_HANG>(this.detach_DON_HANGs));
		this._HANG_XE = default(EntityRef<HANG_XE>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MaXe
	{
		get
		{
			return this._MaXe;
		}
		set
		{
			if ((this._MaXe != value))
			{
				this.OnMaXeChanging(value);
				this.SendPropertyChanging();
				this._MaXe = value;
				this.SendPropertyChanged("MaXe");
				this.OnMaXeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string TenXe
	{
		get
		{
			return this._TenXe;
		}
		set
		{
			if ((this._TenXe != value))
			{
				this.OnTenXeChanging(value);
				this.SendPropertyChanging();
				this._TenXe = value;
				this.SendPropertyChanged("TenXe");
				this.OnTenXeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string TinhTrang
	{
		get
		{
			return this._TinhTrang;
		}
		set
		{
			if ((this._TinhTrang != value))
			{
				this.OnTinhTrangChanging(value);
				this.SendPropertyChanging();
				this._TinhTrang = value;
				this.SendPropertyChanged("TinhTrang");
				this.OnTinhTrangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Decimal(11,0) NOT NULL")]
	public decimal GiaBan
	{
		get
		{
			return this._GiaBan;
		}
		set
		{
			if ((this._GiaBan != value))
			{
				this.OnGiaBanChanging(value);
				this.SendPropertyChanging();
				this._GiaBan = value;
				this.SendPropertyChanged("GiaBan");
				this.OnGiaBanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string Model
	{
		get
		{
			return this._Model;
		}
		set
		{
			if ((this._Model != value))
			{
				this.OnModelChanging(value);
				this.SendPropertyChanging();
				this._Model = value;
				this.SendPropertyChanged("Model");
				this.OnModelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HopSo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string HopSo
	{
		get
		{
			return this._HopSo;
		}
		set
		{
			if ((this._HopSo != value))
			{
				this.OnHopSoChanging(value);
				this.SendPropertyChanging();
				this._HopSo = value;
				this.SendPropertyChanged("HopSo");
				this.OnHopSoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhienLieu", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string NhienLieu
	{
		get
		{
			return this._NhienLieu;
		}
		set
		{
			if ((this._NhienLieu != value))
			{
				this.OnNhienLieuChanging(value);
				this.SendPropertyChanging();
				this._NhienLieu = value;
				this.SendPropertyChanged("NhienLieu");
				this.OnNhienLieuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KieuDanDong", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string KieuDanDong
	{
		get
		{
			return this._KieuDanDong;
		}
		set
		{
			if ((this._KieuDanDong != value))
			{
				this.OnKieuDanDongChanging(value);
				this.SendPropertyChanging();
				this._KieuDanDong = value;
				this.SendPropertyChanged("KieuDanDong");
				this.OnKieuDanDongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauSac", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string MauSac
	{
		get
		{
			return this._MauSac;
		}
		set
		{
			if ((this._MauSac != value))
			{
				this.OnMauSacChanging(value);
				this.SendPropertyChanging();
				this._MauSac = value;
				this.SendPropertyChanged("MauSac");
				this.OnMauSacChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KmDaDi", DbType="Int NOT NULL")]
	public int KmDaDi
	{
		get
		{
			return this._KmDaDi;
		}
		set
		{
			if ((this._KmDaDi != value))
			{
				this.OnKmDaDiChanging(value);
				this.SendPropertyChanging();
				this._KmDaDi = value;
				this.SendPropertyChanged("KmDaDi");
				this.OnKmDaDiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongXe", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string DongXe
	{
		get
		{
			return this._DongXe;
		}
		set
		{
			if ((this._DongXe != value))
			{
				this.OnDongXeChanging(value);
				this.SendPropertyChanging();
				this._DongXe = value;
				this.SendPropertyChanged("DongXe");
				this.OnDongXeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSanXuat", DbType="Int NOT NULL")]
	public int NamSanXuat
	{
		get
		{
			return this._NamSanXuat;
		}
		set
		{
			if ((this._NamSanXuat != value))
			{
				this.OnNamSanXuatChanging(value);
				this.SendPropertyChanging();
				this._NamSanXuat = value;
				this.SendPropertyChanged("NamSanXuat");
				this.OnNamSanXuatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XuatXu", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string XuatXu
	{
		get
		{
			return this._XuatXu;
		}
		set
		{
			if ((this._XuatXu != value))
			{
				this.OnXuatXuChanging(value);
				this.SendPropertyChanging();
				this._XuatXu = value;
				this.SendPropertyChanged("XuatXu");
				this.OnXuatXuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string MoTa
	{
		get
		{
			return this._MoTa;
		}
		set
		{
			if ((this._MoTa != value))
			{
				this.OnMoTaChanging(value);
				this.SendPropertyChanging();
				this._MoTa = value;
				this.SendPropertyChanged("MoTa");
				this.OnMoTaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Anh
	{
		get
		{
			return this._Anh;
		}
		set
		{
			if ((this._Anh != value))
			{
				this.OnAnhChanging(value);
				this.SendPropertyChanging();
				this._Anh = value;
				this.SendPropertyChanged("Anh");
				this.OnAnhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangXe", DbType="Int NOT NULL")]
	public int MaHangXe
	{
		get
		{
			return this._MaHangXe;
		}
		set
		{
			if ((this._MaHangXe != value))
			{
				if (this._HANG_XE.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaHangXeChanging(value);
				this.SendPropertyChanging();
				this._MaHangXe = value;
				this.SendPropertyChanged("MaHangXe");
				this.OnMaHangXeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoSan", DbType="Bit")]
	public System.Nullable<bool> CoSan
	{
		get
		{
			return this._CoSan;
		}
		set
		{
			if ((this._CoSan != value))
			{
				this.OnCoSanChanging(value);
				this.SendPropertyChanging();
				this._CoSan = value;
				this.SendPropertyChanged("CoSan");
				this.OnCoSanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XE_DON_HANG", Storage="_DON_HANGs", ThisKey="MaXe", OtherKey="MaXe")]
	public EntitySet<DON_HANG> DON_HANGs
	{
		get
		{
			return this._DON_HANGs;
		}
		set
		{
			this._DON_HANGs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANG_XE_XE", Storage="_HANG_XE", ThisKey="MaHangXe", OtherKey="MaHangXe", IsForeignKey=true)]
	public HANG_XE HANG_XE
	{
		get
		{
			return this._HANG_XE.Entity;
		}
		set
		{
			HANG_XE previousValue = this._HANG_XE.Entity;
			if (((previousValue != value) 
						|| (this._HANG_XE.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._HANG_XE.Entity = null;
					previousValue.XEs.Remove(this);
				}
				this._HANG_XE.Entity = value;
				if ((value != null))
				{
					value.XEs.Add(this);
					this._MaHangXe = value.MaHangXe;
				}
				else
				{
					this._MaHangXe = default(int);
				}
				this.SendPropertyChanged("HANG_XE");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_DON_HANGs(DON_HANG entity)
	{
		this.SendPropertyChanging();
		entity.XE = this;
	}
	
	private void detach_DON_HANGs(DON_HANG entity)
	{
		this.SendPropertyChanging();
		entity.XE = null;
	}
}

public partial class tintuc_chiTietSLXResult
{
	
	private int _MaTin;
	
	private string _Anh;
	
	private string _MoTa;
	
	private string _NoiDung;
	
	private System.DateTime _NgayTao;
	
	private System.Nullable<int> _LuotXem;
	
	public tintuc_chiTietSLXResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTin", DbType="Int NOT NULL")]
	public int MaTin
	{
		get
		{
			return this._MaTin;
		}
		set
		{
			if ((this._MaTin != value))
			{
				this._MaTin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Anh
	{
		get
		{
			return this._Anh;
		}
		set
		{
			if ((this._Anh != value))
			{
				this._Anh = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string MoTa
	{
		get
		{
			return this._MoTa;
		}
		set
		{
			if ((this._MoTa != value))
			{
				this._MoTa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NoiDung
	{
		get
		{
			return this._NoiDung;
		}
		set
		{
			if ((this._NoiDung != value))
			{
				this._NoiDung = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date NOT NULL")]
	public System.DateTime NgayTao
	{
		get
		{
			return this._NgayTao;
		}
		set
		{
			if ((this._NgayTao != value))
			{
				this._NgayTao = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
	public System.Nullable<int> LuotXem
	{
		get
		{
			return this._LuotXem;
		}
		set
		{
			if ((this._LuotXem != value))
			{
				this._LuotXem = value;
			}
		}
	}
}
#pragma warning restore 1591
